package sk.tsystems.akademia.VideoArt;

import java.text.DateFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.List;
import java.util.Locale;

import sk.tsystems.akademia.VideoArt.Dao.CelebrityDao;
import sk.tsystems.akademia.VideoArt.Dao.GenreDao;
import sk.tsystems.akademia.VideoArt.Dao.ReviewDao;
import sk.tsystems.akademia.VideoArt.Dao.VideoArtDao;
import sk.tsystems.akademia.VideoArt.Model.Celebrity;
import sk.tsystems.akademia.VideoArt.Model.Genre;
import sk.tsystems.akademia.VideoArt.Model.Movie;
import sk.tsystems.akademia.VideoArt.Model.Review;
import sk.tsystems.akademia.VideoArt.Model.TvSeries;
import sk.tsystems.akademia.VideoArt.Model.VideoArt;

/**
 * Hello world!
 *
 */
public class App 
{
    @SuppressWarnings("null")
	public static void main( String[] args ) throws ParseException
    {
////    		Genre
//        GenreDao gd=new GenreDao();
//        Genre genre =new Genre();
//        genre.setName("Sci-fi");
//        genre.setDescription("Sci-fi");
//        gd.saveGenre(genre);
//        genre =new Genre();
//        genre.setName("Akčný");
//        genre.setDescription("Akčný");
//        gd.saveGenre(genre);
//        genre =new Genre();
//        genre.setName("Komédia");
//        genre.setDescription("Komédia");
//        gd.saveGenre(genre);
//        genre =new Genre();
//        genre.setName("Thriller");
//        genre.setDescription("Thriller");
 //   	gd.saveGenre(genre);
//        genre =new Genre();
//        genre.setName("Drama");
//        genre.setDescription("Drama");
//        gd.saveGenre(genre);
////    	 Review
//        ReviewDao rd= new ReviewDao();
//        Review review = new Review();
//        review.setRating(8);
//        review.setText("Konečná 1");
//        rd.saveReview(review);
//        review = new Review();
//        review.setRating(6);
//        review.setText("Konečná 2");
//        rd.saveReview(review);
//        review = new Review();
//        review.setRating(10);
//        review.setText("Enderova hra 1");
//        rd.saveReview(review);
//        review = new Review();
//        review.setRating(9);
//        review.setText("Enderova hra 2");
//        rd.saveReview(review);
//        review = new Review();
//        review.setRating(6);
//        review.setText("Enderova hra 3");
//        rd.saveReview(review);
//        review = new Review();
//        review.setRating(4);
//        review.setText("Hodinový manžel 1");
//        rd.saveReview(review);
//        review = new Review();
//        review.setRating(6);
//        review.setText("Hodinový manžel 2");
//        rd.saveReview(review);
//        review = new Review();
//        review.setRating(8);
//        review.setText("Hodinový manžel 3");
//        rd.saveReview(review);
//        review = new Review();
//        review.setRating(6);
//        review.setText("Myšlienky vraha 1");
//        rd.saveReview(review);
//        review = new Review();
//        review.setRating(2);
//        review.setText("Námořní vyšetřovací služba 1");
//        rd.saveReview(review);
//        review = new Review();
//        review.setRating(6);
//        review.setText("Námořní vyšetřovací služba 2");
//        rd.saveReview(review);
//        review = new Review();
//        review.setRating(6);
//        review.setText("Námořní vyšetřovací služba 3");
//        rd.saveReview(review);
//        review = new Review();
//        review.setRating(5);
//        review.setText("Škorpión 1");
//        rd.saveReview(review);        
//        review = new Review();
//        review.setRating(9);
//        review.setText("Škorpión 2");
//        rd.saveReview(review);
////    	 Celebrity
//    	CelebrityDao cd = new CelebrityDao();
//   	DateFormat format = new SimpleDateFormat("d.MM.yyyy", Locale.ENGLISH);
//    	Celebrity celebrity = new Celebrity();
//    	celebrity.setDateOdfBirth(format.parse("24.06.1991"));
//    	celebrity.setFirstName("Shemar");
//    	celebrity.setSurname("Moore");
//    	cd.saveCelebrity(celebrity);
//    	celebrity = new Celebrity();
//    	celebrity.setDateOdfBirth(format.parse("2.06.1981"));
//    	celebrity.setFirstName("Thomas");
//    	celebrity.setSurname("Gibson");
//    	cd.saveCelebrity(celebrity);
//    	celebrity = new Celebrity();
//    	celebrity.setDateOdfBirth(format.parse("4.12.1971"));
//    	celebrity.setFirstName("Mandy");
//    	celebrity.setSurname("Patinkin");
//    	cd.saveCelebrity(celebrity);
//    	celebrity = new Celebrity();
//    	celebrity.setDateOdfBirth(format.parse("13.03.1978"));
//    	celebrity.setFirstName("Asa");
//    	celebrity.setSurname("Butterfield");
//    	cd.saveCelebrity(celebrity);
//    	celebrity = new Celebrity();
//    	celebrity.setDateOdfBirth(format.parse("30.10.1982"));
//    	celebrity.setFirstName("Abigail");
//    	celebrity.setSurname("Breslin");
//    	cd.saveCelebrity(celebrity);
//    	celebrity = new Celebrity();
//    	celebrity.setDateOdfBirth(format.parse("24.9.1959"));
//    	celebrity.setFirstName("Gavin");
//    	celebrity.setSurname("Hood");
//    	cd.saveCelebrity(celebrity);
//    	celebrity = new Celebrity();
//    	celebrity.setDateOdfBirth(format.parse("1.1.1976"));
//    	celebrity.setFirstName("Jee-woon");
//    	celebrity.setSurname("Kim");
//    	cd.saveCelebrity(celebrity);
//    	celebrity = new Celebrity();
//    	celebrity.setDateOdfBirth(format.parse("2.02.1941"));
//    	celebrity.setFirstName("Tomáš");
//    	celebrity.setSurname("Svoboda");
//    	cd.saveCelebrity(celebrity);
//    	celebrity = new Celebrity();
//    	celebrity.setDateOdfBirth(format.parse("4.07.1968"));
//    	celebrity.setFirstName("Richard");
//    	celebrity.setSurname("Shepard");
//    	cd.saveCelebrity(celebrity);
//    	celebrity = new Celebrity();
//    	celebrity.setDateOdfBirth(format.parse("19.03.1955"));
//    	celebrity.setFirstName("Charles");
//    	celebrity.setSurname("Haid");
//    	cd.saveCelebrity(celebrity);
////    	VideoArt
//    	VideoArtDao vd = new VideoArtDao();
//    	VideoArt videoArtMovie =new Movie();
//    	videoArtMovie.setName("Konečná");
//    	videoArtMovie.setYearOfPublication(2013);
//    	vd.saveVideoArt(videoArtMovie);
//    	videoArtMovie =new Movie();
//    	videoArtMovie.setName("Enderova hra");
//    	videoArtMovie.setYearOfPublication(2013);
//    	vd.saveVideoArt(videoArtMovie);
//    	videoArtMovie =new Movie();
//    	videoArtMovie.setName("Hodinový manžel ");
//    	videoArtMovie.setYearOfPublication(2014);
//    	vd.saveVideoArt(videoArtMovie);
//    	VideoArt videoArtSerial =new TvSeries();
//    	videoArtSerial.setName("Myšlenky zločince");
//    	videoArtSerial.setYearOfPublication(2005);
//    	vd.saveVideoArt(videoArtSerial);
//    	videoArtSerial =new TvSeries();
//    	videoArtSerial.setName("Námořní vyšetřovací služba");
//    	videoArtSerial.setYearOfPublication(2003);
//    	vd.saveVideoArt(videoArtSerial);
//    	videoArtSerial =new TvSeries();
//    	videoArtSerial.setName("Škorpión");
//    	videoArtSerial.setYearOfPublication(2014);
//    	vd.saveVideoArt(videoArtSerial);
//    //	 add connection
//    	Genre loadGenre1 = JpaHelper.getEntityManager().find(Genre.class,136L);
//    	Genre loadGenre2 = JpaHelper.getEntityManager().find(Genre.class,137L);
//    	Genre loadGenre3 = JpaHelper.getEntityManager().find(Genre.class,138L);
//    	Genre loadGenre4 = JpaHelper.getEntityManager().find(Genre.class,139L);
//    	Genre loadGenre5 = JpaHelper.getEntityManager().find(Genre.class,140L);
//
//    	Movie loadMovie1= JpaHelper.getEntityManager().find(Movie.class, 164L);
//    	Movie loadMovie2= JpaHelper.getEntityManager().find(Movie.class, 165L);
//    	Movie loadMovie3= JpaHelper.getEntityManager().find(Movie.class, 166L);
//    	JpaHelper.beginTransaction();
//    	loadMovie1.addGenres(loadGenre2);
//    	loadMovie1.addGenres(loadGenre4);
//    	loadMovie2.addGenres(loadGenre1);
//    	loadMovie2.addGenres(loadGenre2);
//    	loadMovie3.addGenres(loadGenre3);
//    	JpaHelper.commitTransaction();
//    	TvSeries loadTvSeries1=JpaHelper.getEntityManager().find(TvSeries.class, 167L);
//    	TvSeries loadTvSeries2=JpaHelper.getEntityManager().find(TvSeries.class, 168L);
//    	TvSeries loadTvSeries3=JpaHelper.getEntityManager().find(TvSeries.class, 169L);
//    	JpaHelper.beginTransaction();
//    	loadTvSeries1.addGenres(loadGenre4);
//    	loadTvSeries1.addGenres(loadGenre5);
//    	loadTvSeries2.addGenres(loadGenre2);
//    	loadTvSeries2.addGenres(loadGenre5);
//    	loadTvSeries2.addGenres(loadGenre3);
//    	loadTvSeries3.addGenres(loadGenre5);
//    	loadTvSeries3.addGenres(loadGenre2);
//    	JpaHelper.commitTransaction();
//    	Review loadReview1=JpaHelper.getEntityManager().find(Review.class,141L);
//    	Review loadReview2=JpaHelper.getEntityManager().find(Review.class,142L);
//    	Review loadReview3=JpaHelper.getEntityManager().find(Review.class,143L);
//    	Review loadReview4=JpaHelper.getEntityManager().find(Review.class,144L);
//    	Review loadReview5=JpaHelper.getEntityManager().find(Review.class,145L);
//    	Review loadReview6=JpaHelper.getEntityManager().find(Review.class,146L);
//    	Review loadReview7=JpaHelper.getEntityManager().find(Review.class,147L);
//    	Review loadReview8=JpaHelper.getEntityManager().find(Review.class,148L);
//    	Review loadReview9=JpaHelper.getEntityManager().find(Review.class,149L);
//    	Review loadReview10=JpaHelper.getEntityManager().find(Review.class,150L);
//    	Review loadReview11=JpaHelper.getEntityManager().find(Review.class,151L);
//    	Review loadReview12=JpaHelper.getEntityManager().find(Review.class,152L);
//    	Review loadReview13=JpaHelper.getEntityManager().find(Review.class,153L);
//    	Review loadReview14=JpaHelper.getEntityManager().find(Review.class,154L);
//    	JpaHelper.beginTransaction();
//    	loadReview1.setReviewed(loadMovie1);
//    	loadReview2.setReviewed(loadMovie1);
//    	loadReview3.setReviewed(loadMovie2);
//    	loadReview4.setReviewed(loadMovie2);
//    	loadReview5.setReviewed(loadMovie2);
//    	loadReview6.setReviewed(loadMovie3);
//    	loadReview7.setReviewed(loadMovie3);
//    	loadReview8.setReviewed(loadMovie3);
//    	loadReview9.setReviewed(loadTvSeries1);
//    	loadReview10.setReviewed(loadTvSeries2);
//    	loadReview11.setReviewed(loadTvSeries2);
//    	loadReview12.setReviewed(loadTvSeries2);
//    	loadReview13.setReviewed(loadTvSeries3);
//    	loadReview14.setReviewed(loadTvSeries3);
//    	JpaHelper.commitTransaction();
//    	JpaHelper.beginTransaction();
//    	loadMovie1.setLength(107);
//    	loadMovie2.setLength(114);
//    	loadMovie3.setLength(100);
//    	loadTvSeries1.setSeriesCount(11);
//    	loadTvSeries1.setEpisodeCount(185);
//    	loadTvSeries1.setEndYear();
//    	loadTvSeries2.setEpisodeCount(258);
//    	loadTvSeries2.setSeriesCount(13);
//    	loadTvSeries1.setEndYear();
//    	loadTvSeries3.setEpisodeCount(22);
//    	loadTvSeries3.setSeriesCount(1);
//    	loadTvSeries1.setEndYear();
//    	JpaHelper.commitTransaction();
//    	Celebrity loadCelebrity1=JpaHelper.getEntityManager().find(Celebrity.class, 155L);
//    	Celebrity loadCelebrity2=JpaHelper.getEntityManager().find(Celebrity.class, 156L);
//    	Celebrity loadCelebrity3=JpaHelper.getEntityManager().find(Celebrity.class, 157L);
//    	Celebrity loadCelebrity4=JpaHelper.getEntityManager().find(Celebrity.class, 158L);
//    	Celebrity loadCelebrity5=JpaHelper.getEntityManager().find(Celebrity.class, 159L);
//    	Celebrity loadCelebrity6=JpaHelper.getEntityManager().find(Celebrity.class, 160L);
//    	Celebrity loadCelebrity7=JpaHelper.getEntityManager().find(Celebrity.class, 161L);
//    	Celebrity loadCelebrity8=JpaHelper.getEntityManager().find(Celebrity.class, 162L);
//    	Celebrity loadCelebrity9=JpaHelper.getEntityManager().find(Celebrity.class, 163L);
//    	Celebrity loadCelebrity10=JpaHelper.getEntityManager().find(Celebrity.class, 170L);
//    	VideoArt loadVideoArt1=JpaHelper.getEntityManager().find(Movie.class, 164L);
//    	VideoArt loadVideoArt2=JpaHelper.getEntityManager().find(Movie.class, 165L);
//    	VideoArt loadVideoArt3=JpaHelper.getEntityManager().find(Movie.class, 166L);
//    	VideoArt loadVideoArt4=JpaHelper.getEntityManager().find(TvSeries.class, 167L);
//    	VideoArt loadVideoArt5=JpaHelper.getEntityManager().find(TvSeries.class, 168L);
//    	VideoArt loadVideoArt6=JpaHelper.getEntityManager().find(TvSeries.class, 169L);
//    	JpaHelper.beginTransaction();
//    	loadVideoArt1.addDirectors(loadCelebrity7);
//    	loadVideoArt2.addDirectors(loadCelebrity6);
//    	loadVideoArt3.addDirectors(loadCelebrity8);
//    	loadVideoArt4.addDirectors(loadCelebrity9);
//    	loadVideoArt5.addDirectors(loadCelebrity10);
//    	loadVideoArt6.addDirectors(loadCelebrity6);
//    	loadVideoArt1.addActors(loadCelebrity4);
//    	loadVideoArt1.addActors(loadCelebrity3);
//    	loadVideoArt2.addActors(loadCelebrity1);
//    	loadVideoArt2.addActors(loadCelebrity3);
//    	loadVideoArt3.addActors(loadCelebrity2);
//    	loadVideoArt3.addActors(loadCelebrity3);
//    	loadVideoArt3.addActors(loadCelebrity5);
//    	loadVideoArt3.addActors(loadCelebrity7);
//    	loadVideoArt4.addActors(loadCelebrity3);
//    	loadVideoArt4.addActors(loadCelebrity5);
//    	loadVideoArt5.addActors(loadCelebrity4);
//    	loadVideoArt5.addActors(loadCelebrity3);
//    	loadVideoArt5.addActors(loadCelebrity9);
//    	loadVideoArt6.addActors(loadCelebrity4);
//    	loadVideoArt6.addActors(loadCelebrity10);
//    	JpaHelper.commitTransaction();
    	
    	VideoArtDao vad =new VideoArtDao();
    	vad.showMovieFromYear(2013);
    	vad.countOfSerials();
    	vad.countOfMovies();
    	//vad.showMovieWithActor("Patinkin");
    	
    	JpaHelper.close();
    }
}
